title: George Salafatinos
email:
description: >-
  George Salafatinos — thoughts on math, philosophy, music, and interesting problems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.georgesalafatinos.com" # the base hostname & protocol for your site
twitter_username: GSalafatinos
github_username: George-salafatinos
linkedin_url: "https://www.linkedin.com/in/george-salafatinos-675662179"
flatio_url: "https://flat.io/@george_salafatinos/published"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

plugins:
  - jekyll-feed
